In [6]:
#numpy is used to work with array
import numpy as np

In [7]:
# 1-D Array
a=np.array([3,4,5])
a

array([3, 4, 5])

In [8]:
#2-D array
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [9]:
#initialize all the elements to 0
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#Arrangr some numbers between x and y at an interval of 2
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
#print even numbers
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [12]:
#arrange 10 numbers betweeen 5 and 10
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [13]:
#even numbers between 0 and 10
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
np.random.random((3,4))

array([[0.40615144, 0.04984167, 0.13994311, 0.32096069],
       [0.5390206 , 0.88068843, 0.82269739, 0.70191823],
       [0.73243352, 0.51767934, 0.99704542, 0.32363113]])

In [15]:
np.random.rand(3,4)

array([[0.115182  , 0.90698166, 0.90937096, 0.15240893],
       [0.36379549, 0.94684905, 0.22513512, 0.43914223],
       [0.40034898, 0.28805541, 0.11103261, 0.36732968]])

In [16]:
#matrices filling same number 
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [17]:
#isnpecting array
a=np.array([[2,3,4],[5,6,7]])
a.ndim #gives no.of rows 

2

In [18]:
a.shape #gives shape of the array

(2, 3)

In [19]:
#no.of elements
print(a.size)

6


In [20]:
type(a)

numpy.ndarray

In [21]:
#sum of nd array
np.sum(a)

27

In [22]:
#adding column elements
np.sum([[1,3],[4,5]],axis=0)

array([5, 8])

In [23]:
np.subtract(3,4)

-1

In [24]:
np.divide(2,3)

0.6666666666666666

In [25]:
a=np.array([2,3,4])
b=np.array([4,6,7])
np.multiply(a,b)

array([ 8, 18, 28])

In [26]:
print("exponent :",np.exp(a))
print("square root :",np.sqrt(a))
print("cos:",np.cos(a))
print("sin :",np.sin(a))
print("log :",np.log(a))

exponent : [ 7.3890561  20.08553692 54.59815003]
square root : [1.41421356 1.73205081 2.        ]
cos: [-0.41614684 -0.9899925  -0.65364362]
sin : [ 0.90929743  0.14112001 -0.7568025 ]
log : [0.69314718 1.09861229 1.38629436]


In [27]:
#array comaprison
a=np.array([1,2,3])
b=np.array([2,4,5])
c=np.array([1,2,3])

np.equal(a,c)

array([ True,  True,  True])

In [28]:
np.array_equal(a,c)

True

In [29]:
np.array_equal(a,b)

False

In [30]:
#aggregate functions
a=np.array([[1,2,3,4,5]])
c=np.array([1,2,3])
print("sum :",np.sum(a))
print("Mean :",np.mean(a))
print("Median:",np.median(a))
print("Min:",np.min(a))
print("Standard deviation :",np.std(a))
print("Correlation Coefficient :",np.corrcoef(a))

sum : 15
Mean : 3.0
Median: 3.0
Min: 1
Standard deviation : 1.4142135623730951
Correlation Coefficient : 1.0


In [31]:
#concept of broadcasting
a=np.array([[1,2,3],[7,0,3],[2,5,7]])
b=np.array([[1,2,3]])
print("First array :\n",a,'\n')
print("Second array :\n",b,'\n')
print(a+b)

First array :
 [[1 2 3]
 [7 0 3]
 [2 5 7]] 

Second array :
 [[1 2 3]] 

[[ 2  4  6]
 [ 8  2  6]
 [ 3  7 10]]


In [32]:
print(a*b)

[[ 1  4  9]
 [ 7  0  9]
 [ 2 10 21]]


In [33]:
#indexing and slicing
a=['m','o','n','t','y','p','y','t','h','o','n']
a[2:9]

['n', 't', 'y', 'p', 'y', 't', 'h']

In [34]:
a=np.array([[1,2,3],[7,0,3],[2,5,7]])
a[0:3,0:1]

array([[1],
       [7],
       [2]])

In [35]:
#numpy vs list memory size
import sys

l=range(1000)
print("size of list:",sys.getsizeof(1)*len(l))

a=np.arange(1000)
print("size of list:",a.size*a.itemsize)

size of list: 28000
size of list: 4000


In [36]:
import sys
import time
import numpy as np

# let's declare the size
Size = 100000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result = [(x*y) for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)

# Calculating time for NumPy array
start = time.time()
result = arr1*arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

print("\nThis means NumPy array is faster than Python List")

Time for Python List in msec:  31.9976806640625
Time for NumPy array in msec:  0.0

This means NumPy array is faster than Python List
